### ISSUE TITLE
Failed to install amuse due to "Failed building wheel for amuse-simplex"

### ISSUE THREAD

**Issue by Anit5577** [amusecode/amuse#1057]
I had a working amuse installation (2022 package version) and wanted to update that recently. To do that, I created a completely new environment for a clean install following the installation procedure provided using pip.

Ubuntu 22.04.4 LTS
Python 3.10.12

However, this time I ran into issues with a failed installation "Failed building wheel for amuse-simplex", see the attached copy of the error [Amuse_install_fail.pdf](https://github.com/amusecode/amuse/files/15467418/Amuse_install_fail.pdf)". It then stops the installation.

On the surface, it looks similar to some of the other recent install failures I have found in the issues folder, but I am unsure how to resolve it.
[Amuse_install_fail.pdf](https://github.com/amusecode/amuse/files/15402520/Amuse_install_fail.pdf)

**Comment by LourensVeen** [comment]
Yes, this is probably the same issue. The PyPI packages are currently broken, or rather some of the community codes don't build in modern environments and this then breaks the entire installation.

PyPI isn't really the right place to distribute AMUSE actually, because AMUSE has non-Python dependencies and PyPI just cannot deal with those. I'm making good progress with Conda packages, but it turns out to require a good amount of reengineering to make them work, so that's ongoing.

In the mean time, you could either keep using the current version, or install the development version from source. To do that, first install the dependencies, including the Python ones, according to the documentation, and then do ***not*** do

```bash
pip install amuse-framework
pip install amuse-$(community_code_name)
```

but skip to

```bash
git clone https://github.com/amusecode/amuse.git
cd amuse
pip install -e .
python setup.py develop_build
```
You're likely to still get some build failures for some of the packages, but that shouldn't keep you from using the rest. We'll be fixing the broken community codes as part of our Conda packaging efforts in the coming months.
