### ISSUE TITLE
Replace nose for tests with pytest

### ISSUE THREAD

**Issue by rieder** [amusecode/amuse#196]
from the nose website (http://nose.readthedocs.io/en/latest/): 

> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

**Comment by ipelupessy** [comment]
I think consensus is that py.test is most pleasurable to work with; don't know about nose2
prerequisite wise plain unittest/unittest2 would be best? Also are we using anything from nose beyond test discovery (@arjenve)?

**Comment by arjenve** [comment]
Yes, we base everything on  the python unittest module  and use nosetest for discovery. As nose simply works and we do not need anything else of it (i.e. maintenance is not necessary) we can just keep using it. Having an alternative is nice ofcourse, but I consider this low priority. (I>E. if the alternative can also be called on a directory and then runs all unit tests etc.)

**Comment by egpbos** [comment]
I'm having some issues with filtering tests. There are command line options to use some kind of regex (syntax unknown, because undocumented as far as I could find) to either match or exclude specific files, directories OR test names, but not all simultaneously. For instance, I can't figure out how to filter tests `test10` and `test11` in `test.core_tests.test_rotation.TestRotations`, which are currently giving me trouble in the macOS Travis build (#262). I would prefer to just get the Travis build working first and fix these remaining issues with tests 10 and 11 later, so as not to confuse PRs with "sub quests" that pop up along the way, stifling progress. So in this sense, nose is not really working well for me.

It seems like pytest has more powerful filtering (https://docs.pytest.org/en/latest/usage.html#specifying-tests-selecting-tests).

**Comment by rieder** [comment]
Nose is currently still a prerequisite for AMUSE, but I don't think it should be one. Tests can be run with pytest or something else, so nose should be optional.
Is it OK to remove it from the prerequisite checks in configure?

**Comment by ipelupessy** [comment]
if you can confirm that it works with pytest, you can remove it (although, you need 1 of them? I am always wondering if you can specify more complicated dependencies, such as <or>...)...would you add pytest instead?

**Comment by rieder** [comment]
Pytest works for me so far, will test it a bit more but I think we can replace nose with it without problems.

**Comment by rieder** [comment]
@ipelupessy did you find any problems using the tests with pytest?

**Comment by ipelupessy** [comment]
tests with pytest run, but need a bit more baby sitting (see #504) ...have you tried to e.g. run all the code tests in succesion?

**Comment by rieder** [comment]
This should be done by the end of this week. Mostly works.
