### ISSUE TITLE
Flash installation

### ISSUE THREAD

**Issue by nluetzge** [amusecode/amuse#274]
Is there any documentation on how to install Flash with AMUSE? I have registered and downloaded the code and I put it in src/amuse/community/flash/src/ ... However now when I'm trying to run make flash.code it still gives me the download error. After checking the makefile it looks like it gives you the error no matter if you run it with DOWNLOAD_CODES=1 or not. So I removed the error it raises but then in complains that it cannot fine a rule to make all. Something is messed up when it tries to create the libflash.a (it tries to run a make on the src level) but I'm not deep enough into makefiles to figure out how to change it. Since this is a non-standard installation (because the download has to be done manually) there should be some instructions on how to proceed from there. Maybe I just missed them somewhere.

**Comment by joshuawall** [comment]
Hello Nora,

   Did you first compile a problem in FLASH itself? If you haven't yet, I highly recommend taking a look at the FLASH user's guide at http://www.flash.uchicago.edu/site/flashcode for the version you downloaded.

    Note that FLASH itself is similar to AMUSE in that it is a framework with many internal units for different physics for the simulation (HD, MHD, RHD, lasers, source heating, etc etc). So first you need to set up a problem of your choosing and then compile for that problem. Once you have compiled (and set up the flash.par file) the AMUSE makefile will link to the compiled flash4 executable and copy the flash.par file over. I suggest starting with the simple 3d Sedov test problem in source/Simulation/SimulationMain/Sedov.

    FLASH is a very complex, but very capable code. It takes some effort to master, but it is well worth the work. The user guide and the flash users email group (searching the archive is a must often) are you're best friends in sorting out issues.

    As a final note, FLASH also has its own Makefile structure that is machine specific. There are prototypes for different OSs found in the sites/Prototypes folder.

    Hope that helps!

    Josh

**Comment by nluetzge** [comment]
Hi Josh,

Thanks I think this was the thing I was missing that I have to compile flash first and then link it with amuse. Will try that. 

Cheers, 
Nora

**Comment by vantonuccio** [comment]
Dear all, I am afraid I am experiencing the same problems experienced by NL. I have a copy of FLASH (v. 4.3) and I have already compiled a specific problem which I have previously run. 
I have downloaded from amuse.org the current release (11.2), installed and successfully compiled some codes, e.g sei, using the following command:

-> gmake -j 4 sei.code

My main target however is to compile and use the FLASH interface, and here I fail. I have modified the Makefile of the FLASH interface as follows:

Line 18: drive_loc = <directory where the particular FLASH problem was set up>

and set the DOWNLOAD_CODES env. variable before compiling:

setenv DOWNLOAD_CODES 1

The output of the compilation command:

-> gmake -j 4 flash.code

is the following:


> gmake -j 4 flash.code
/opt/Python-2.7.9/bin/python2.7 setup.py -v build_code --inplace --clean=yes --code-name=flash
running build_code
building code flash
make -C src/amuse/community/flash clean
make[1]: Entering directory `/home-volume/van/software/python/amuse-11.2/src/amuse/community/flash'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
rm -f -f *.so *.o *.pyc worker_code.cc worker_code.h #flash.par
rm -f *~ flash_worker worker_code.f90
make -C src clean
make: Entering an unknown directory
make: *** src: No such file or directory.  Stop.
make: Leaving an unknown directory
make[1]: *** [clean] Error 2
make[1]: Leaving directory `/home-volume/van/software/python/amuse-11.2/src/amuse/community/flash'
make -C src/amuse/community/flash all
make[1]: Entering directory `/home-volume/van/software/python/amuse-11.2/src/amuse/community/flash'
make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
/home/van/software/python/amuse-11.2/build.py --type=f90 interface.py FlashInterface -o worker_code.f90
check step
make -C . download
make[2]: Entering directory `/home-volume/van/software/python/amuse-11.2/src/amuse/community/flash'

*** Unfortunately due to flash download restrictions;
*** FLASH CANNOT be download automatically by this makefile
*** Please register and download flash yourself

make[3]: *** No rule to make target `raise_error'.  Stop.
make[2]: *** [download] Error 2
make[2]: Leaving directory `/home-volume/van/software/python/amuse-11.2/src/amuse/community/flash'
make[1]: *** [src/makefile] Error 2
make[1]: Leaving directory `/home-volume/van/software/python/amuse-11.2/src/amuse/community/flash'
default ... failed


======================================
Many thanks in advance for any help.

**Comment by rnaranjoromero** [comment]
Try with:
gmake flash.code

Also, the error may result because you need to previously download the flash code first.
