### ISSUE TITLE
move code data, lib and script

### ISSUE THREAD

**Issue by ipelupessy** [amusecode/amuse#391]
currently AMUSE installs in /share:
- (static) input data for the codes, which could move to data directory of the codes themselves 
- compiled libraries, which normally are found in some prefix//lib directory (some packaging software will complain about libs in non standard location
- a build.py script which should be installed in prefix/bin (together with an amuse.sh, currently not installed)
- config.mk, not sure what convention is for this...

one drawback: the location of these are set now by single AMUSE_DIR environment variable, this would need to change too

**Comment by rieder** [comment]
Do you mean /share or something like AMUSE_DIR/share (I can't find it)?

Which libraries are installed by AMUSE currently? Do you mean stopping conditions etc.?

amuse.sh is probably not necessary anymore, certainly not with a pip installation - I haven't used it in ages...

config.mk: if it is at all possible, I think it would be good to keep this shared between amuse packages (so installed by amuse-framework which all other packages depend on). Then at least we will have the same settings for all packages, which will prevent major problems due to changed compilers etc.

**Comment by ipelupessy** [comment]
I mean the $prefix/share/amuse/lib etc (ie in the repository lib & data with the libraries like stopping conditions, and the static code input data)

ok, I am also not using it..the only script would then the build.py (needs rename) - its handy for people also to get going interfacing a code...(but now it is only usable if you would know where to find it) 

config.mk would indeed be shared (but I am not sure if the share/amuse dir is the best location for it). Its mainly needed for compilation (although, maybe also for running..), it will be found when compiling through the setup.py (but you need an environment variable for a "direct" compile...

**Comment by ipelupessy** [comment]
btw I have also zapped the support directory from the install (#389) - you think that is ook?

**Comment by ipelupessy** [comment]
one thing that still has me confused is whether there is a way to determine (ie read) with a pip install where the config.mk file ends up during the build...

**Comment by rieder** [comment]
Not sure. But I guess there would be a way to determine the current $SITE_PACKAGES (or something), and I think $AMUSE_ROOT will be $SITE_PACKAGES/amuse...
