### ISSUE TITLE
Installation issues with Simplex and Galaxia

### ISSUE THREAD

**Issue by fertiss** [amusecode/amuse#505]
I cannot install amuse via
pip install amuse
in Ubuntu 16.04. I have installed all prerequisites apart from libmpfr6. I use libmpfr4. I do not know if this is the problem. The output is 592 lines. I give the basic errors here:
 Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:

ERROR: Failed building wheel for amuse-simplex
    Running setup.py clean for amuse-simplex
  Failed to build amuse-galaxia amuse-simplex
  ERROR: Could not build wheels for amuse-galaxia, amuse-simplex which use PEP 517 and cannot be installed directly

**Comment by ipelupessy** [comment]
Hi, 

this is probably a problem with MPI and one of the codes in AMUSE (simplex) which uses deprecated cpp bindings. You can force the install to complete by setting an environment variable: 
```
export AMUSE_ALLOW_BUILD_FAILURES=all
```
before install. (of course, the failed codes will not work...)

**Comment by ipelupessy** [comment]
@rieder maybe we should remove simplex from the amuse pip package for now? It can always be added explicitly with pip install amuse-simplex ..

**Comment by ipelupessy** [comment]
I don't know the reason for the failure of galaxia this was noted before #467

**Comment by rieder** [comment]
I think the problem with Simplex is both what @ipelupessy mentioned and that it needs hdf5 libraries (at the time amuse-framework is installed). Not sure if we mention this clearly enough. 
I don't think we should remove it from the amuse package just now.

**Comment by pasolar** [comment]
hi, I cannot install amuse via
pip install amuse in macOS, because I have this problem:
I tried to use your command (export AMUSE_ALLOW_BUILD_FAILURES=all) but it didn't work

ERROR: Command errored out with exit status 1:
   command: /Users/paulo/anaconda2/envs/amuse.2.7py/bin/python /Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-GxVJ2R/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'amuse-framework>=12.1.3[MPI]' 'amuse-athena>=12.1.3' 'amuse-bhtree>=12.1.3' 'amuse-brutus>=12.1.3' 'amuse-bse>=12.1.3' 'amuse-capreole>=12.1.3' 'amuse-evtwin>=12.1.3' 'amuse-fastkick>=12.1.3' 'amuse-fi>=12.1.3' 'amuse-fractalcluster>=12.1.3' 'amuse-gadget2>=12.1.3' 'amuse-galactics>=12.1.3' 'amuse-galaxia>=12.1.3' 'amuse-halogen>=12.1.3' 'amuse-hermite>=12.1.3' 'amuse-hop>=12.1.3' 'amuse-huayno>=12.1.3' 'amuse-kepler>=12.1.3' 'amuse-kepler-orbiters>=12.1.3' 'amuse-mameclot>=12.1.3' 'amuse-mercury>=12.1.3' 'amuse-mmams>=12.1.3' 'amuse-ph4>=12.1.3' 'amuse-seba>=12.1.3' 'amuse-secularmultiple>=12.1.3' 'amuse-smalln>=12.1.3' 'amuse-sphray>=12.1.3' 'amuse-sse>=12.1.3' 'amuse-twobody>=12.1.3'
       cwd: None
  Complete output (130 lines):
  DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  Collecting amuse-framework>=12.1.3[MPI]
    Using cached https://files.pythonhosted.org/packages/6c/bd/08d3db4d89d4419b73f8f9633355b6ac04c6d8f2d8df7ef227ed5e5c573d/amuse-framework-12.1.3.post1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting amuse-athena>=12.1.3
    Using cached https://files.pythonhosted.org/packages/a8/31/1a6a3df93e53a91b9cc3e570a22d0774943b4abc0808f9bfc154a83c94de/amuse-athena-12.1.3.post1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/paulo/anaconda2/envs/amuse.2.7py/bin/python /Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-eF81TW/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel amuse-framework
         cwd: None
    Complete output (111 lines):
    DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    Collecting setuptools
      Using cached https://files.pythonhosted.org/packages/f9/d3/955738b20d3832dfa3cd3d9b07e29a8162edb480bf988332f5e6e48ca444/setuptools-44.0.0-py2.py3-none-any.whl
    Collecting wheel
      Using cached https://files.pythonhosted.org/packages/00/83/b4a77d044e78ad1a45610eb88f745be2fd2c6d658f9798a15e384b7d57c9/wheel-0.33.6-py2.py3-none-any.whl
    Collecting amuse-framework
      Using cached https://files.pythonhosted.org/packages/6c/bd/08d3db4d89d4419b73f8f9633355b6ac04c6d8f2d8df7ef227ed5e5c573d/amuse-framework-12.1.3.post1.tar.gz
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
        Preparing wheel metadata: started
        Preparing wheel metadata: finished with status 'done'
    Collecting pip>=19.0.0
      Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
    Collecting h5py>=1.1.0
      Using cached https://files.pythonhosted.org/packages/2c/47/e0d58be6f292684a4541d10b1da953542ff679f3ffc6096bee73634832b1/h5py-2.10.0-cp27-cp27m-macosx_10_6_intel.whl
    Collecting docutils>=0.6
      Using cached https://files.pythonhosted.org/packages/3a/dc/bf2b15d1fa15a6f7a9e77a61b74ecbbae7258558fcda8ffc9a6638a6b327/docutils-0.15.2-py2-none-any.whl
    Collecting nose>=0.11.1
      Using cached https://files.pythonhosted.org/packages/99/4f/13fb671119e65c4dce97c60e67d3fd9e6f7f809f2b307e2611f4701205cb/nose-1.3.7-py2-none-any.whl
    Collecting numpy>=1.2.2
      Using cached https://files.pythonhosted.org/packages/09/96/84cf406fe7d589f3dba9fc0f737e65985a3526c6d8c783f02d4b5a10825d/numpy-1.16.6-cp27-cp27m-macosx_10_9_x86_64.whl
    Collecting six
      Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
    Building wheels for collected packages: amuse-framework
      Building wheel for amuse-framework (PEP 517): started
      Building wheel for amuse-framework (PEP 517): finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/paulo/anaconda2/envs/amuse.2.7py/bin/python /Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/tmpEmZyge
           cwd: /private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-install-778VfG/amuse-framework
      Complete output (74 lines):
      running bdist_wheel
      running build
      running configure_codes
      Warning: Can't read registry to find the necessary compiler setting
      Make sure that Python modules _winreg, win32api or win32con are installed.
      get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize NAGFCompiler
      customize AbsoftFCompiler
      Could not locate executable f90
      Could not locate executable f77
      customize IBMFCompiler
      Could not locate executable xlf90
      Could not locate executable xlf
      customize IntelFCompiler
      Could not locate executable ifort
      Could not locate executable ifc
      customize GnuFCompiler
      Could not locate executable g77
      customize G95FCompiler
      Could not locate executable g95
      customize PGroupFCompiler
      Could not locate executable pgfortran
      don't know how to compile Fortran code on platform 'posix'
      Running configure for AMUSE
      config.mk not generated; output of configure:
      checking for gcc... gcc
      checking whether the C compiler works... no
      configure: error: in `/private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-install-778VfG/amuse-framework':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
  
      Traceback (most recent call last):
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
          main()
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 182, in build_wheel
          metadata_directory)
        File "/private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-sdaA9_/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 209, in build_wheel
          wheel_directory, config_settings)
        File "/private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-sdaA9_/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-sdaA9_/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-sdaA9_/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 77, in <module>
          scripts=[ "bin/amusifier" ],
        File "/private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-sdaA9_/overlay/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/distutils/core.py", line 151, in setup
          dist.run_commands()
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/distutils/dist.py", line 953, in run_commands
          self.run_command(cmd)
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/distutils/dist.py", line 972, in run_command
          cmd_obj.run()
        File "/private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-sdaA9_/overlay/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run
          self.run_command('build')
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/distutils/cmd.py", line 326, in run_command
          self.distribution.run_command(command)
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/distutils/dist.py", line 972, in run_command
          cmd_obj.run()
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/distutils/command/build.py", line 127, in run
          self.run_command(cmd_name)
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/distutils/cmd.py", line 326, in run_command
          self.distribution.run_command(command)
        File "/Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/distutils/dist.py", line 972, in run_command
          cmd_obj.run()
        File "/private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-install-778VfG/amuse-framework/support/setup_codes.py", line 1169, in run
          raise Exception("configure failed")
      Exception: configure failed
      ----------------------------------------
      ERROR: Failed building wheel for amuse-framework
      Running setup.py clean for amuse-framework
    Failed to build amuse-framework
    ERROR: Could not build wheels for amuse-framework which use PEP 517 and cannot be installed directly
    ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/paulo/anaconda2/envs/amuse.2.7py/bin/python /Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-eF81TW/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel amuse-framework Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/paulo/anaconda2/envs/amuse.2.7py/bin/python /Users/paulo/anaconda2/envs/amuse.2.7py/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/bn/mj43q7r53tx42h6kx57q2sn80000gn/T/pip-build-env-GxVJ2R/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'amuse-framework>=12.1.3[MPI]' 'amuse-athena>=12.1.3' 'amuse-bhtree>=12.1.3' 'amuse-brutus>=12.1.3' 'amuse-bse>=12.1.3' 'amuse-capreole>=12.1.3' 'amuse-evtwin>=12.1.3' 'amuse-fastkick>=12.1.3' 'amuse-fi>=12.1.3' 'amuse-fractalcluster>=12.1.3' 'amuse-gadget2>=12.1.3' 'amuse-galactics>=12.1.3' 'amuse-galaxia>=12.1.3' 'amuse-halogen>=12.1.3' 'amuse-hermite>=12.1.3' 'amuse-hop>=12.1.3' 'amuse-huayno>=12.1.3' 'amuse-kepler>=12.1.3' 'amuse-kepler-orbiters>=12.1.3' 'amuse-mameclot>=12.1.3' 'amuse-mercury>=12.1.3' 'amuse-mmams>=12.1.3' 'amuse-ph4>=12.1.3' 'amuse-seba>=12.1.3' 'amuse-secularmultiple>=12.1.3' 'amuse-smalln>=12.1.3' 'amuse-sphray>=12.1.3' 'amuse-sse>=12.1.3' 'amuse-twobody>=12.1.3' Check the logs for full command output.

**Comment by rieder** [comment]
@pasolar I've moved your question to #565 as it is separate from this issue.

**Comment by pasolar** [comment]
@rieder oka thanks
