### ISSUE TITLE
doesn't work with mode updated version of mpi4py

### ISSUE THREAD

**Issue by hilaglanz** [amusecode/amuse#61]
on file rfi/channel.py line 1253 should be "rc.threads" instead of "rc.threading"

**Comment by iambernie** [comment]
You probably mean: _should be "rc.threads" instead of "rc.threaded"_ since the variable was renamed from rc.threaded to rc.threads [at some point](https://bitbucket.org/mpi4py/mpi4py/commits/edca4fc223dd285eea7c4228044cc1cd36c33225?at=master).
This was discussed a while ago in issue #26 and PR #27 should resolve the issue. If you "git checkout" the most recent commit, you probably won't run into this anymore.

**Comment by ipelupessy** [comment]
has this been resolved?

**Comment by ipelupessy** [comment]
I think it is fixed by #27
