### ISSUE TITLE
EVtwin wind settings

### ISSUE THREAD

**Issue by AlexOlza** [amusecode/amuse#624]
Hello there. 
I'm running a simulation with both MESA and EVtwin, but I'm unable to switch off the stellar wind with EVtwin. Is this possible?

More precisely, I can switch off RBG and Ostar wind settings but not AGB. My attempt:

````
evtwin=EVtwin()
evtwin.set_RGB_wind_setting(0.0)
evtwin.set_Ostar_wind_setting(0.0)
evtwin.set_AGB_wind_setting(0) 
print(evtwin.parameters)
````

raises the exception `AmuseException: Error when calling 'set_AGB_wind_setting' of a 'EVtwin', errorcode is -1`

I have also tried `evtwin.set_AGB_wind_setting(False) ` and `evtwin.set_AGB_wind_setting(0.0) ` with the same result. `evtwin.set_AGB_wind_setting(2) ` succeeds but it's not switching off the wind.

Thank you!

**Comment by ipelupessy** [comment]
the permissible values for AGB winds are 1 or 2 (corresponding to Wachter and Vasilis-Wood formulation. They are implemented with simple multipliers though, it needs a (small) source code change to have them both zero - it could be that something bad happens if that is the case, or it could just work: do you want to try? (if yes I push the change...;-) )

**Comment by alexolza** [comment]
No, it's fine, I just needed to be sure about what each value is doing. I'm stuck at AMUSE-12, but I actually prefer to use Watcher's wind than no wind at all. Is this kind of stuff documented somewhere? I found documentation for MESA but not for EVtwin :(
Thank you for your answer!

**Comment by ipelupessy** [comment]
closing. Can be reopend if needed
