### ISSUE TITLE
Add an external pressure in Fi and/or Gadget2 

### ISSUE THREAD

**Issue by ReinosoB** [amusecode/amuse#729]
I would like to include an external pressure to stabilize a cloud of SPH particles. For this I am trying to modify the momentum equation in Fi and also in Gadget2, in analogy to the method described by Clark et al. 2011 (https://ui.adsabs.harvard.edu/abs/2011ApJ...727..110C/abstract) 
<img width="366" alt="clark2011_modification" src="https://user-images.githubusercontent.com/48846569/107423983-60f7ac80-6b1d-11eb-809d-18c18e14ff18.png">

I guess I should modify the file "entdot.f90" in Fi, or the file "hydra.c" in Gadget2, but I don't know which units to use.
Say that I want to include Pext=1 g cm^-1 s^-2. Which number should I write in those files?  

Thanks

**Comment by MJCWilhelm** [comment]
That's going to depend on the unit system used by the code, which in general is some dimensionless system (I think). The converter you pass when initializing Fi or Gadget is what handles the conversion from units in amuse to whatever the SPH code uses. If you want to implement this with a fixed unit system, you have to figure out the exact unit system and the conversion between the two systems.

A more elegant solution would be to add the external pressure as a parameter in the interface. In that case the unit conversion can be handled by amuse. You would have to add a way to pass the parameter from the interface.c or interface.F90 to the relevant routine in the code. You can study those files and interface.py to see how to set up that you can set it as a parameter. There are also some tutorials on interface building in the amuse documentation. 

Another thought I had is that this might be good place to use Bridge, because the external pressure results in a velocity kick. However, it does use the smoothing kernel to determine the direction of the acceleration this pressure causes, so it's not straight forward to get the direction.

**Comment by ReinosoB** [comment]
@MJCWilhelm Many thanks for your answer. Before attempting the more elegant solution I want to try 
the simplest (at least for me) method, using always the same converter in my python script. So the
question is, how is this conversion between the two systems made? where can I find that information?

**Comment by MJCWilhelm** [comment]
I'm not entirely sure. The code release papers would be a good place to start, and maybe some early SPH review papers. And maybe @ipelupessy could comment on this, as the developer of Fi?

**Comment by ReinosoB** [comment]
@MJCWilhelm  after many attempts I think I've figured out this issue. I might try the more elegant solution in the future.
Many thanks for your help!
