### ISSUE TITLE
Dynamical Friction

### ISSUE THREAD

**Issue by arpan-das-astrophysics** [amusecode/amuse#765]
Hello, I am trying to simulate a cluster and including physics like dynamical friction and feedbacks. I am just double checking if the gravity solver PH4 already accounts for the stellar dynamical friction while accounting for the force between the particles or not? Thank you in advance.

**Comment by spzwart** [comment]
Dear Arpan,

thanks for your question. Ph4 is a general N-body solver. it accounts for
Newton's forces and solves the equations of motion. if you are intetested
in mass segregation, Ph4 would be a fine code to use. If you are intetested
in the dynamical friction due to the gravitational influence of gas, you
will have to bridge Ph4 with a hydodynamics solver. If you are also
interested in the drag between the bodies and the gas, I recomment using an
augmented bridge between de N-body code and the hydrocode. this is all
explained in the AMUSE book,
https://iopscience.iop.org/book/978-0-7503-1320-9, or have a look at the
website amusecode.org. there is a tutorial.

good luck,
Simon

**Comment by arpan-das-astrophysics** [comment]
Hi Simon, 

Thank you for the response. For now, we have a static gas reservoir, and we are not doing the hydro. I am externally incorporating the effect of dynamical friction due to the gas. I am just making sure if the dynamical friction between the stars is already taken account by the PH4 or I have to externally incorporate that as well? Or in in other words, PH4 is already taking into account the eq. 2.10 of the book? 

Best, 
Arpan

**Comment by spzwart** [comment]
Dear Arpan,

Ph4 will properly take the effect of dynamical friction between the stars
into account.

Simon
