### ISSUE TITLE
Having trouble installing amuse-framework through Anaconda

### ISSUE THREAD

**Issue by edrick-afk** [amusecode/amuse#906]
I am an undergraduate student and I have been trying to install amuse through anaconda (inside an environment). However, I have been trouble installing amuse-framework.
Here is the command that I would usually put in:
$ conda create -n amuse python==3.8 openmpi openmpi-mpicc openmpi-mpicxx openmpi-mpifort libgcc gfortran hdf5 FFTW GSL CMake GMP MPFR mpi4py
which preinstall all the prerequisite python packages as well as the compilers along with the environment. Then I would type 
$conda activate amuse
$pip install amuse-framework
But then the wheel-building process for amuse-framework will exit with an error:
[amuse-framework error.pdf](https://github.com/amusecode/amuse/files/10070456/amuse-framework.error.pdf)
Two things I noticed is that 1). the C compiler is not working, even though I have openmpi-mpicc installed; also, it seems like my computer would automatically go to distutils instead of setuptools as default. I did not do anything to the root/base, so is there any way that I can set setuptools as default? Or is there something else that I need to do in order for the computer to access setuptools first?

Thank you in advance

**Comment by rieder** [comment]
Conda and AMUSE is not a happy combination...
The main problem I notice is that in the compiler used here is `clang`, which we don't support for AMUSE (you need `gcc`).
There have been some (partially successful) attempts at installing AMUSE with (ana)conda (you can search for them here), but I don't have a test environment for this myself unfortunately so I can't provide clear instructions.
On macOS, we highly recommend installing AMUSE using macports to install prerequisites instead of anaconda. Homebrew will also work.

**Comment by rieder** [comment]
(see issues #235 and #525)

**Comment by edrick-afk** [comment]
Thank you very much for the information! I didn't know clang could be a problem here. I shall give macport a try then and see if it works.

**Comment by edrick-afk** [comment]
I used macport (along with openmpi) and still had trouble downloading amuse-framework. It is saying that my python interpreter is too old even though the version is >=3.5 (it is python 3.9.13).
[Macport installation error.pdf](https://github.com/amusecode/amuse/files/10071009/Macport.installation.error.pdf)
It also still has the setuptools/distutils error. How would I resolve that issue?

**Comment by rieder** [comment]
continued in #907, closing.
