### ISSUE TITLE
conda on apple silicon

### ISSUE THREAD

**Issue by GijsVermarien** [amusecode/amuse#983]
I see that codes like bhtree and hop failed to build- that’s really not good. Those are ‘core’ packages… can you find out why these failed to build?

_Originally posted by @rieder in https://github.com/amusecode/amuse/issues/980#issuecomment-1709703826_

Created a new post to keep things separated, this discussion wasn't really about MESA anymore.

**Comment by GijsVermarien** [comment]
Here are the error messages for bhtree and hop. It seems to be a problem that certain functions aren't loaded correctly ? 

[make bhtree.code.txt](https://github.com/amusecode/amuse/files/12546641/make.bhtree.code.txt)
[make hop.code.txt](https://github.com/amusecode/amuse/files/12546642/make.hop.code.txt)

**Comment by rieder** [comment]
right - the problem is that you're compiling with clang rather than gcc. We don't support clang currently.

**Comment by LourensVeen** [comment]
Just to note: conda-forge uses clang and gfortran to build all its Mac packages. There are GCC Conda-packages for Mac, but conda-forge doesn't use them by default. So I guess I'll have to see whether it's easier to get conda-forge to build with a different C++ compiler or to get AMUSE and the community codes to build with clang...

I do seem to have managed to build an Intel Mac package for amuse-framework now (on my Linux laptop, they cross-compile!), and my next step is to try to figure out how to get it to do the same for Apple Silicon. If I can make that work, then you'll be able to conda install amuse there...

**Comment by LourensVeen** [comment]
Yes, why not? I'm doing all platforms at the same time, so there may be some overlap with #984, but people specifically interested in Apple Silicon would then be able to follow here, and maybe we can do a bit of testing here once I've got something testable together.

Latest update: conda claims to have built some Apple Silicon packages for amuse-framework (on my Linux laptop!), but I have no idea if they actually work. I'm going to try to make a package for `ph4` next (because I want to test the Sapporo packages), and then do `bhtree`, for which I should be able to make Apple Silicon packages as well.

At that point I would be looking for a volunteer to see if they can get it to run on actual Apple hardware. I'll keep you posted :smile:.

**Comment by GijsVermarien** [comment]
Cool, happy to guinea pig any binaries as soon as you're ready!
